language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast-finish: true

install:
  - composer install

before_script:
  - export PATH="$TRAVIS_BUILD_DIR/_build:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

script:
  - phpcs --standard=.phpcs.xml "$TRAVIS_BUILD_DIR"

after_success:
  - deploy-phpdoc-branch.sh

before_deploy:
  - deploy-phpdoc-release.sh
  - create-release-archive.sh "$TRAVIS_TAG"

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: pico-release-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    tags: true
    php: 5.3

sudo: false
